# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Heady Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Heady Test
  pod 'Alamofire'
  pod 'SVProgressHUD'

  target 'Heady TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Heady TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
